package ba.unsa.etf.rpr.project.items;

public enum BookCategory {
    FICTIONAL, BIOGRAPHY, NOVELS, CHILDREN, CRIME,
    MISTERY, ENTERTAINMENT, ROMANCE, THRILLER, POETRY,
    GENERAL, BUSINESS, ART, DICTIONARY, LANGUAGES,
    MEDICAL, ENGINEERING, RELIGION, PROGRAMMING, OTHER
}
